/// <autosync enabled="true" />
/// <reference path="bootstrap.js" />
/// <reference path="jquery.history.js" />
/// <reference path="jquery.validate.js" />
/// <reference path="jquery.validate.unobtrusive.js" />
/// <reference path="jquery-1.10.2.js" />
/// <reference path="jquery-ui-1.11.4.js" />
/// <reference path="jquery-ui-1.11.4.min.js" />
/// <reference path="knockout.mapping-latest.js" />
/// <reference path="knockout-3.4.0.js" />
/// <reference path="modernizr-2.6.2.js" />
/// <reference path="respond.js" />
/// <reference path="sammy-0.7.5.min.js" />
/// <reference path="toastr.min.js" />
/// <reference path="view scripts/bookdetails/show.js" />
/// <reference path="view scripts/booksmanagement/createedit.js" />
/// <reference path="view scripts/booksmanagement/index.js" />
/// <reference path="view scripts/categoriesmanagement/index.js" />
/// <reference path="View Scripts/Home/index.js" />
/// <reference path="view scripts/librarian/index.js" />
